on:
  push:
    branches:
      - main
      - longer
  pull_request:
    branches:
      - main
      - longer

jobs:
  test:
@@ -21,11 +21,10 @@ jobs:
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Run tests
      run: |
        pytest
        echo "No tests to run"  # Or replace with pytest if tests exist ve 
